export type Hue = "teal" | "purple" | "amber";
export type Store = {
  id: string;
  name: string;
  icon: string;
  cat: string;
  hue: Hue;
  dist: number;
  item: string;
  open: number;
  tag: string;
};

export const INDOOR: Store[] = [
  {
    id: "zara",
    name: "Zara",
    icon: "👗",
    cat: "Fashion",
    hue: "purple",
    dist: 6,
    item: "Oversized Wool Hoodie",
    open: 899,
    tag: "Hoodies",
  },
  {
    id: "nespresso",
    name: "Nespresso Bar",
    icon: "☕",
    cat: "Coffee aisle",
    hue: "amber",
    dist: 9,
    item: "Flat White + Croissant",
    open: 85,
    tag: "Coffee",
  },
  {
    id: "istore",
    name: "iStore",
    icon: "📱",
    cat: "Electronics",
    hue: "teal",
    dist: 14,
    item: "AirPods Pro 2",
    open: 5499,
    tag: "Audio",
  },
  {
    id: "nike",
    name: "Nike Lab",
    icon: "👟",
    cat: "Sportswear",
    hue: "teal",
    dist: 11,
    item: "Pegasus 41 Running Shoes",
    open: 2599,
    tag: "Shoes",
  },
  {
    id: "sushi",
    name: "Kauai Sushi Bar",
    icon: "🍣",
    cat: "Food court",
    hue: "purple",
    dist: 17,
    item: "Salmon Rainbow Platter",
    open: 189,
    tag: "Sushi",
  },
  {
    id: "aesop",
    name: "Aesop",
    icon: "🧴",
    cat: "Beauty",
    hue: "amber",
    dist: 8,
    item: "Resurrection Hand Balm",
    open: 520,
    tag: "Skincare",
  },
  {
    id: "hm",
    name: "H&M Studio",
    icon: "🧥",
    cat: "Fashion",
    hue: "purple",
    dist: 19,
    item: "Puffer Jacket",
    open: 1299,
    tag: "Jackets",
  },
  {
    id: "exclusive",
    name: "Exclusive Books",
    icon: "📚",
    cat: "Books",
    hue: "teal",
    dist: 13,
    item: "Signed Hardcover Bundle",
    open: 640,
    tag: "Books",
  },
  {
    id: "lindt",
    name: "Lindt Boutique",
    icon: "🍫",
    cat: "Confectionery",
    hue: "amber",
    dist: 5,
    item: "Truffle Gift Box",
    open: 320,
    tag: "Gifts",
  },
];

export const OUTDOOR: Store[] = [
  {
    id: "vida",
    name: "Vida e Caffè",
    icon: "☕",
    cat: "Street café",
    hue: "amber",
    dist: 22,
    item: "Double Cappuccino",
    open: 48,
    tag: "Coffee",
  },
  {
    id: "incredible",
    name: "Incredible Connection",
    icon: "💻",
    cat: "Electronics",
    hue: "teal",
    dist: 41,
    item: "Mechanical Keyboard",
    open: 1899,
    tag: "Tech",
  },
  {
    id: "adidas",
    name: "Adidas Originals",
    icon: "👟",
    cat: "Sneakers",
    hue: "teal",
    dist: 35,
    item: "Samba OG",
    open: 2199,
    tag: "Shoes",
  },
  {
    id: "kfc",
    name: "Mochi Ramen House",
    icon: "🍜",
    cat: "Restaurant",
    hue: "purple",
    dist: 28,
    item: "Tonkotsu Ramen",
    open: 165,
    tag: "Ramen",
  },
  {
    id: "markham",
    name: "Markham",
    icon: "👔",
    cat: "Menswear",
    hue: "purple",
    dist: 46,
    item: "Slim Chino + Tee Combo",
    open: 799,
    tag: "Fashion",
  },
  {
    id: "dischem",
    name: "Dis-Chem",
    icon: "💊",
    cat: "Pharmacy",
    hue: "teal",
    dist: 31,
    item: "Vitamin C Bundle",
    open: 260,
    tag: "Health",
  },
  {
    id: "woolies",
    name: "Woolworths Food",
    icon: "🥑",
    cat: "Grocer",
    hue: "amber",
    dist: 49,
    item: "Weekend Brunch Box",
    open: 410,
    tag: "Groceries",
  },
  {
    id: "cotton",
    name: "Cotton On",
    icon: "🧢",
    cat: "Streetwear",
    hue: "purple",
    dist: 38,
    item: "Graphic Hoodie",
    open: 499,
    tag: "Hoodies",
  },
  {
    id: "sushi2",
    name: "Tokyo Street Sushi",
    icon: "🍣",
    cat: "Takeaway",
    hue: "amber",
    dist: 25,
    item: "Dragon Roll Combo",
    open: 210,
    tag: "Sushi",
  },
  {
    id: "samsung",
    name: "Samsung Experience",
    icon: "⌚",
    cat: "Electronics",
    hue: "teal",
    dist: 44,
    item: "Galaxy Watch 7",
    open: 5999,
    tag: "Wearables",
  },
  {
    id: "bike",
    name: "Cycle Lab",
    icon: "🚲",
    cat: "Outdoor",
    hue: "purple",
    dist: 33,
    item: "Smart Bike Light",
    open: 690,
    tag: "Cycling",
  },
];

export const TICKS = [
  "Agent negotiating {tag}…",
  "Price dropped by {n}%…",
  "Checking stock levels…",
  "Loyalty points verified",
  "Counter-offer sent: R{p}",
  "Bundling discount detected",
  "Handshake signed ✓",
  "Comparing 3 nearby rivals…",
];

export const hueVar: Record<Hue, string> = {
  teal: "var(--primary)",
  purple: "var(--secondary)",
  amber: "var(--accent)",
};

export const fill = (t: string, s: Store) =>
  t
    .replace("{tag}", s.tag.toLowerCase())
    .replace("{n}", String(5 + Math.floor(Math.random() * 20)))
    .replace("{p}", String(Math.round(s.open * (0.7 + Math.random() * 0.2))));
